### ISSUE TITLE
File I/O error in Windows where opening subtitles in different drive

### ISSUE THREAD

**Issue by mbattaglia** [carsonip/Penguin-Subtitle-Player#72] opened 2020-04-30 17:07 UTC
Hi, I was trying to play some subtitles and but kept getting a "File I/O" error. After some troubleshooting I realized that I can consistenly reproduce this error if the subtitles are on a different drive (Penguin player in D:/ and files in C:/).

Tried to look for some logs but was not able to find them.

**Comment by carsonip** [comment] 2020-04-30 17:20
Hi @mbattaglia, the file IO error popup is only added in v1.3.0. Can you play the subtitle with v1.2.1? I'll look into this issue tomorrow.

**Comment by mbattaglia** [comment] 2020-04-30 18:34
Hi, I just tested in v1.2.1 and this issue is not present.

**Comment by carsonip** [comment] 2020-05-01 06:46
By "the issue is not present" do you mean you can play the subtitle file successfully? I cannot reproduce this issue in Windows.

**Comment by mbattaglia** [comment] 2020-05-01 06:52
What I tried to say is that I can play the subtitles in v1.2.1 even if the .stl file is on another drive than the .exe.

**Comment by carsonip** [comment] 2020-05-01 06:54
Is that a stl file or srt file?

**Comment by mbattaglia** [comment] 2020-05-01 07:28
I shouldnt log into GitHub before my coffee... I mean a .srt file.

**Comment by mbattaglia** [comment] 2020-05-01 07:35
Just added you to a private repo containing a .gif with the walkthrough of the error.

**Comment by carsonip** [comment] 2020-05-01 09:34
Thanks for taking the time to create a gif to illustrate the problem. I'll look into it and get back to you once I get something.

**Comment by carsonip** [comment] 2020-06-21 16:47
Hi @mbattaglia, sorry for replying so late. I can finally reproduce the issue. It is not a problem about different drives, but more about the file path containing non-ascii character in Windows. I will fix this ASAP. Thanks again for the bug report and the gif.

**Comment by carsonip** [comment] 2020-06-21 17:15
Clarification: It happens in Windows only, when the file path contains non-ascii characters. It will cause a problem with the charset detection step. This problem exists prior to 1.3.0, just that 1.3.0 caught the error and displayed it, i.e. charset detection will always fail in Windows if the file path has non-ascii chars. This issue will be fixed in 1.3.1.

**Closed** 2020-06-22 15:47 UTC
Labels: bug
